name: C/C++ CI

on: [push]

jobs:
  centos:
    runs-on: ubuntu-latest
    container:
      image: centos/devtoolset-7-toolchain-centos7
      options: -u root
    steps:
    - name: Install dependencies
      run: |
        yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        yum install -y make boost-devel catch-devel readline-devel
    - name: Checkout
      uses: actions/checkout@v2
    - name: make junit
      run: |
        make
        make junit || true
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1.6
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        files: tests/*.xml

  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        sudo apt update -y
        sudo apt install -y make g++ libboost-dev catch libreadline-dev
    - name: Checkout
      uses: actions/checkout@v2
    - name: make junit
      run: |
        make
        make junit || true
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1.6
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        files: tests/*.xml
