name: C/C++ CI

on: [push]

jobs:
  almalinux:
    runs-on: ubuntu-latest
    name: Test compile on latest AlmaLinux
    container:
      image: almalinux
    steps:
    - name: Install dependencies
      run: |
        dnf install -y epel-release
        dnf install -y make g++ catch-devel readline-devel yaml-cpp-devel spdlog-devel
    - name: Checkout
      uses: actions/checkout@v4
    - name: make junit
      run: |
        make
        make junit || true

  ubuntu:
    runs-on: ubuntu-latest
    name: Test compile on Ubuntu
    steps:
    - name: Install dependencies
      run: |
        sudo apt update -y
        sudo apt install -y make g++ catch libreadline-dev libyaml-cpp-dev libspdlog-dev
    - name: Checkout
      uses: actions/checkout@v4
    - name: make junit
      run: |
        make
        make junit || true
